name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: lukeroyibm/ibmfunction-on-code-engine-nodejs:$(date +%s)
    steps:
#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v1
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v1
    - name: Display Image Name and Tag
      run: echo $IMAGE
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: $IMAGE

